version: "3.9"

volumes:
  web_data:

services:
  web:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "8001:80"
    links:
      - php
    restart: always
    depends_on:
      - php
    volumes:
      - ./build:/usr/share/nginx/html
  php:
    image: php:7-fpm
    restart: always
    volumes:
      - ./build:/usr/share/nginx/html
    user: root
